# Generated by Django 3.0.6 on 2020-05-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='menu',
        ),
    ]
